### PR TITLE
Feature/token

### PR DESCRIPTION
**Pull request by AlWestVT**
Simple correction of EIGHT to EIGHTH in 3 Tokens

### CODE REVIEW

**Comment by AlWestVT** [comment]
As this comes from the Python code @saniemi  should review this PR also.

**Comment by iRhysBradbury** [comment]
Why is this "EIGHT"?
Reference: https://github.com/ONSdigital/address-index-data/blob/develop/DataScience/ProbabilisticParser/common/tokens.py#L68

**Comment by iRhysBradbury** [comment]
This branch doesn't look quite right; I will fix; please don't merge.

**Comment by saniemi** [comment]
Because I cannot spell.. this needs to be fixed in Python as well. I can make a hotfix, retrain a new model, and re-generate the validation results. I doubt that anything changes, but I think we should fix it  nonetheless, as it may change future behaviour. Happy to discuss.

**Pull request closed without merging**
